ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
baseURL = "https://infallible-jang-09ce2a.netlify.app"
languageCode = "en-us"
title = "Firm_name"
theme = "navigator-hugo"
summaryLength = 10
math = true

# Build robots.txt file
enableRobotsTXT = true
# google analytics tracking id
googleAnalytics = ""

enableGitInfo = false
pygmentsCodeFences = true

# Multilangues setup
# Renders the default content language in subdir, e.g. /en/. The root directory / will redirect to /en/
defaultContentLanguageInSubdir = true
DefaultContentLanguage = "en"

# Site Params
[params]
logo = "images/logo.png"

# Gestion des langues : FR / EN / NL / DE
#[[Params.listeLangues]]
#code = "en"
#[[Params.listeLangues]]
#code = "de"

# meta data
author = "Firm_name"
description = "This is meta description"

# Gestion des langues : FR / EN / NL / DE
[Languages]
############ 1 - Site en FRANCAIS
[Languages.de]
weight = 1
languageCode = "fr-fr"
title = "FRANCAIS Example site multi-language"
dateFormat = "2 January 2006"

home = "Home"
logo = "images/logo.png"
menufixed = false

footerDescription = "FRANCAIS Integer posuere erat a ante venenati dapibus posuere velit aliquet. Fusce dapibus, tellus cursus commodo, tortor mauris sed posuere."
footerServiceTitle = "FRANCAIS Services"
footerQuicklinkTitle = "FRANCAIS Quick links"
footerAboutTitle = "FRANCAIS About"
footerSubscribeTitle = "FRANCAIS Subscribe"

# Hero Area Section
[Languages.de.params.hero]
enable  = true
heading = "FRANCAIS We love to make brands grow"
description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At quo dolor est incidunt suscipit minima, alias numquam voluptatum rerum porro. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Labore at laboriosam unde repellat id expedita quae quisquam libero officia consequatur."
button  = true
btnText = "Know More"
btnURL  = "https://themefisher.com/"
videoThumb = "images/slider/video-player-thumb.jpg"
videoURL   = "https://www.youtube.com/embed/g3-VxLQO7do"

# About 2 Section
[Languages.de.params.aboutSm]
enable  = true
title   = "FRANCAIS We have explored the digital landscape with passion for a long time"
description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quae deleniti ipsa labore necessitatibus culpa veritatis quo accusantium, neque enim ea ad eaque iure, quas tempore velit, quibusdam dolor illo! Explicabo. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid quisquam maiores iste soluta, nihil dolorem?"

# Blog Section On Homepage
[Languages.de.params.blog]
enable  = true
topTitle= "OUR UNTOLD STORY"
title   = "FRANCAIS Blog."
subtitle= "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum reiciendis quasi itaque, obcaecati atque sit!"

# Contact Section
[Languages.de.params.contact]
enable  = true
topTitle= "DROP US A NOTE"
title   = "FRANCAIS Contact Us."
subtitle= "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum reiciendis quasi itaque, obcaecati atque sit!"
address = "14/05, Stockhome <br> Victori Palace , United States"
phone   = "(03) 9283 2617"
fax     = "+61 3827 3590"
facebook= "https://www.facebook.com/"
twitter = "https://twitter.com/"
linkedin= "https://www.linkedin.com/"
dribbble= "https://dribbble.com/"
instagram= "https://www.instagram.com/"
mapLatitude = "51.507351"
mapLongitude= "-0.127758"
mapMarker   = "images/marker.png"

# Call to Action Section on About Page
[Languages.de.params.cta]
enable  = true
bg      = "images/call-to-action/call-to-action-bg-2.jpg"
title   = "FRANCAIS Let's Create Something Together"
subtitle= "Proin gravida nibh vel velit auctor aliquet. Aenean sollicudin bibendum auctor, <br> nisi elit consequat ipsum, nesagittis sem nid elit. Duis sed odio sitain elit."
btnText = "Nous contacter"

############# 2 - Site en ENGLISH
[Languages.en]
weight = 2
languageCode = "de"
title = "Firm_name"
dateFormat = "02.01.2006"

home = "Start"
logo = "images/logo.png"
menufixed = false

footerDescription = "Wir sind ein datengetriebenes Beratungsunternehmen. Daten sind unsere Leidenschaft und das Werkzeug für die Lösung wirtschaftlicher Probleme."
footerServiceTitle = "Leistungsspektrum"
footerQuicklinkTitle = "Quicklinks"
footerAboutTitle = "Wer wir sind"
footerSubscribeTitle = "Subscribe"

# Hero Area Section
[Languages.en.params.hero]
enable  = true
heading = "Datengetriebene Beratung"
description = "Wir sind ein datengetriebenes Beratungsunternehmen. Mithilfe statistischer Methoden und Machine Learning unterstützen wir sie dabei, Unternehmensentscheidungen datenbasiert zu treffen. Wir sind überzeugt: Daten sind der Schlüssel zur Effizienz."
#button  = true
#btnText = "Know More"
#btnURL  = "https://themefisher.com/"
videoThumb = "images/slider/video-player-thumb.jpg"
#videoURL   = "https://www.youtube.com/embed/g3-VxLQO7do"

# About 2 Section
[Languages.en.params.aboutSm]
enable  = true
title   = "Mit unserer Leidenschaft für datengetriebene Businesslösungen helfen wir Ihnen dabei, Gewinn aus Ihren Daten zu ziehen"
description = "Verlassen Sie sich bei wichtigen Betriebsentscheidungen nicht auf Faustformeln und bloßes Bauchgefühl. Schöpfen Sie das Potenzial aus, das in Daten steckt. Wir helfen Ihnen dabei, die Effizienz Ihres Unternehmens zu steigern, indem wir Daten generieren, analysieren und basierend auf den erzeugten Erkenntnissen klare Handlungsempfehlungen  ableiten. "

# Blog Section On Homepage
[Languages.en.params.blog]
enable  = true
topTitle= ""
title   = "Analysen"
subtitle= "Hier finden Sie eine Auswahl durchgeführter Analysen"

# Contact Section
[Languages.en.params.contact]
enable  = true
#topTitle= "DROP US A NOTE"
title   = "Kontaktformular"
subtitle= "Schicken Sie uns eine Anfrage über unser Kontaktformular. Wir melden uns umgehend bei Ihnen."
address = "Schulstraße 6 <br> 65618 Selters"
phone   = "0157 50288464"
email = "nicolas.mollier@gmx.de"
#fax     = "+61 3827 3590"
#facebook= "https://www.facebook.com/"
#twitter = "https://twitter.com/"
#linkedin= "https://www.linkedin.com/"
#dribbble= "https://dribbble.com/"
#instagram= "https://www.instagram.com/"
mapLatitude = "50.128039"
mapLongitude= "8.668170"
mapMarker   = "images/marker.png"

# Call to Action Section on About Page
[Languages.en.params.cta]
enable  = true
bg      = "images/call-to-action/call-to-action-bg-2.jpg"
title   = "Let's Create Something Together"
subtitle= "Proin gravida nibh vel velit auctor aliquet. Aenean sollicudin bibendum auctor, <br> nisi elit consequat ipsum, nesagittis sem nid elit. Duis sed odio sitain elit."
btnText = "Contact Us"
name = "contact"
url = "contact"



# We Used Themefisher Icon font for Icon, for more details check this github repository - https://github.com/themefisher/themefisher-font

# Site Menus
[menu]
# Navbar Menus
[[menu.nav]]
name    = "about"
url     = "about"
weight  = 2
[[menu.nav]]
name    = "service"
url     = "service"
weight  = 3
[[menu.nav]]
name    = "portfolio"
url     = "portfolio"
weight  = 4
[[menu.nav]]
name    = "blog"
url     = "blog"
weight  = 5
[[menu.nav]]
name    = "contact"
url     = "contact"
weight  = 6

# Footer Service Menu
[[menu.service]]
name    = "graphicdesign"
url     = "service"
weight  = 1
[[menu.service]]
name    = "webdesign"
url     = "service"
weight  = 2
[[menu.service]]
name    = "webdevelopment"
url     = "service"
weight  = 3

# Footer Quick links Menu
[[menu.quicklink]]
name    = "about"
url     = "about"
weight  = 1
[[menu.quicklink]]
name    = "service"
url     = "service"
weight  = 2
[[menu.quicklink]]
name    = "portfolio"
url     = "portfolio"
weight  = 3
[[menu.quicklink]]
name    = "blog"
url     = "blog"
weight  = 4
